'use client';

import { useState, useEffect, useCallback, Suspense, useMemo } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { Edit2, Trash2, Search, X, Loader2, MessageSquare, Phone, Mail } from 'lucide-react';
import ContactForm from '@/components/admin2/contacts/ContactForm';
import { toast } from 'react-toastify';
import axios from 'axios';
import { useHeaderActions } from '@/context/HeaderActionContext';

function ContactsContent() {
	const router = useRouter();
	const searchParams = useSearchParams();
	const action = searchParams.get('action');
	const editId = searchParams.get('id');

	const [contactsList, setContactsList] = useState<any[]>([]);
	const [isLoading, setIsLoading] = useState(true);
	const [searchTerm, setSearchTerm] = useState('');
	const [filterStatus, setFilterStatus] = useState<string>('all');

	const getCookie = (name: string) => {
		if (typeof document === 'undefined') return '';
		const match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
		if (match) return match[2];
		return '';
	};

	/** Fetch contacts list from the API */
	const fetchContacts = useCallback(async () => {
		setIsLoading(true);
		try {
			const token = getCookie('token');
			const res = await axios.get('/api/v1/contacts', {
				headers: { Authorization: `Bearer ${token}` },
			});
			if (res.data.status) {
				setContactsList(res.data.data || []);
			}
		} catch {
			toast.error('Failed to load contacts');
		} finally {
			setIsLoading(false);
		}
	}, []);

	useEffect(() => {
		fetchContacts();
	}, [fetchContacts]);

	// Note: We don't have an "Add Contact" button in the topbar for the Admin panel 
	// since contacts are typically generated by users on the public site.
	useHeaderActions(null);

	const closeDrawer = () => {
		router.push('/admin2/contacts');
	};

	/** Soft-delete a contact */
	const handleDelete = async (id: string, name: string) => {
		if (!confirm(`Are you sure you want to delete inquiry from "${name}"?`)) return;

		try {
			const token = getCookie('token');
			const res = await axios.delete(`/api/v1/contacts/${id}`, {
				headers: { Authorization: `Bearer ${token}` },
			});
			if (res.data.status) {
				toast.success(res.data.message || 'Contact deleted');
				fetchContacts();
			}
		} catch (error: any) {
			toast.error(error.response?.data?.message || 'Failed to delete contact');
		}
	};

	/** Format status for display */
	const formatStatus = (status: string) => {
		switch (status) {
			case 'new': return { label: 'New', color: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400' };
			case 'in_progress': return { label: 'In Progress', color: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' };
			case 'resolved': return { label: 'Resolved', color: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' };
			case 'spam': return { label: 'Spam', color: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400' };
			default: return { label: status, color: 'bg-secondary-100 text-secondary-700 dark:bg-secondary-800 dark:text-secondary-400' };
		}
	};

	/** Filter contacts */
	const filteredContacts = contactsList.filter((c) => {
		const term = searchTerm.toLowerCase();
		const name = (c.name || '').toLowerCase();
		const email = (c.email || '').toLowerCase();
		const phone = (c.phone || '').toLowerCase();
		
		const matchesSearch = name.includes(term) || email.includes(term) || phone.includes(term);
		const matchesStatus = filterStatus === 'all' || c.status === filterStatus;
		
		return matchesSearch && matchesStatus;
	});

	return (
		<div className="relative min-h-[calc(100vh-80px)]">
			{/* Search & Filters */}
			<div className="bg-white dark:bg-[#1e1e48] p-4 rounded-xl shadow-card border border-secondary-600/10 dark:border-white/5 mb-6 flex flex-wrap items-center gap-3">
				<div className="relative flex-1 min-w-[200px] max-w-md">
					<Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-text-light" />
					<input
						type="text"
						placeholder="Search by name, email, or phone..."
						className="w-full pl-10 pr-4 py-2 bg-secondary-100 dark:bg-[#171738] border border-transparent focus:border-accent rounded-lg outline-none text-text-dark dark:text-secondary-100 text-sm"
						value={searchTerm}
						onChange={(e) => setSearchTerm(e.target.value)}
					/>
				</div>
				<select
					value={filterStatus}
					onChange={(e) => setFilterStatus(e.target.value)}
					className="px-3 py-2 bg-secondary-100 dark:bg-[#171738] border border-transparent focus:border-accent rounded-lg outline-none text-text-dark dark:text-secondary-100 text-sm appearance-none cursor-pointer"
				>
					<option value="all">All Statuses</option>
					<option value="new">New</option>
					<option value="in_progress">In Progress</option>
					<option value="resolved">Resolved</option>
					<option value="spam">Spam</option>
				</select>
			</div>

			{/* Data Table */}
			<div className="bg-white dark:bg-[#1e1e48] rounded-xl shadow-card border border-secondary-600/10 dark:border-white/5 overflow-hidden">
				<div className="overflow-x-auto">
					<table className="w-full text-left border-collapse">
						<thead>
							<tr className="bg-secondary-100 dark:bg-[#171738] text-text-dark dark:text-secondary-200 text-sm font-semibold">
								<th className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5">Date</th>
								<th className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5">Customer</th>
								<th className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5">Service Inquiry</th>
								<th className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5">Status</th>
								<th className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5 text-right">Actions</th>
							</tr>
						</thead>
						<tbody>
							{isLoading ? (
								<tr>
									<td colSpan={5} className="text-center py-12">
										<Loader2 className="w-6 h-6 animate-spin text-accent mx-auto" />
									</td>
								</tr>
							) : filteredContacts.length === 0 ? (
								<tr>
									<td colSpan={5} className="text-center py-12 text-text-light dark:text-secondary-400">
										{searchTerm ? 'No contacts match your search.' : 'No contact inquiries found.'}
									</td>
								</tr>
							) : (
								filteredContacts.map((contact, idx) => {
									const statusDisplay = formatStatus(contact.status);
									return (
										<motion.tr
											initial={{ opacity: 0, y: 10 }}
											animate={{ opacity: 1, y: 0 }}
											transition={{ delay: idx * 0.05 }}
											key={contact.id}
											className="hover:bg-secondary-50 dark:hover:bg-[#171738]/50 transition-colors group"
										>
											<td className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5 text-sm text-text-light dark:text-secondary-300">
												{new Date(contact.createdAt).toLocaleDateString()}
											</td>
											<td className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5">
												<div className="font-medium text-text-dark dark:text-secondary-100">
													{contact.name}
												</div>
												<div className="flex flex-col mt-1 space-y-0.5">
													<div className="flex items-center text-xs text-text-light dark:text-secondary-400">
														<Mail className="w-3 h-3 mr-1" /> {contact.email}
													</div>
													{contact.phone && (
														<div className="flex items-center text-xs text-text-light dark:text-secondary-400">
															<Phone className="w-3 h-3 mr-1" /> {contact.phone}
														</div>
													)}
												</div>
											</td>
											<td className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5 text-sm text-text-dark dark:text-secondary-200">
												{contact.serviceType}
											</td>
											<td className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5">
												<span className={`px-3 py-1 text-xs font-semibold rounded-full ${statusDisplay.color}`}>
													{statusDisplay.label}
												</span>
											</td>
											<td className="px-6 py-4 border-b border-secondary-600/10 dark:border-white/5 text-right">
												<button
													onClick={() => router.push(`/admin2/contacts?action=edit&id=${contact.id}`)}
													className="p-2 text-accent hover:bg-accent/10 rounded-lg transition-colors mr-2"
													title="View / Update"
												>
													<Edit2 className="w-4 h-4" />
												</button>
												<button
													onClick={() => handleDelete(contact.id, contact.name)}
													className="p-2 text-error hover:bg-error/10 rounded-lg transition-colors"
													title="Delete"
												>
													<Trash2 className="w-4 h-4" />
												</button>
											</td>
										</motion.tr>
									);
								})
							)}
						</tbody>
					</table>
				</div>
			</div>

			{/* Slide-out Drawer for View/Edit */}
			<AnimatePresence>
				{(action === 'edit' || action === 'view') && (
					<>
						<motion.div
							initial={{ opacity: 0 }}
							animate={{ opacity: 1 }}
							exit={{ opacity: 0 }}
							onClick={closeDrawer}
							className="fixed inset-0 bg-black/40 backdrop-blur-sm z-40"
						/>
						<motion.div
							initial={{ x: '100%' }}
							animate={{ x: 0 }}
							exit={{ x: '100%' }}
							transition={{ type: 'spring', damping: 25, stiffness: 200 }}
							className="fixed top-0 right-0 h-full w-full max-w-2xl bg-white dark:bg-[#1e1e48] shadow-2xl z-50 overflow-y-auto border-l border-secondary-600/20 dark:border-white/10"
						>
							<div className="sticky top-0 bg-white/80 dark:bg-primary-800/80 backdrop-blur-md px-6 py-4 border-b border-secondary-600/10 dark:border-primary-600/30 flex justify-between items-center z-10">
								<h2 className="text-xl font-bold text-text-dark dark:text-secondary-100 flex items-center">
									<MessageSquare className="w-5 h-5 mr-2 text-accent" />
									Contact Inquiry Details
								</h2>
								<button onClick={closeDrawer} className="p-2 hover:bg-secondary-100 dark:hover:bg-primary-700 rounded-full text-text-light transition-colors">
									<X className="w-5 h-5" />
								</button>
							</div>
							<div className="p-6">
								<ContactForm
									onClose={closeDrawer}
									editId={editId}
									onSaved={fetchContacts}
								/>
							</div>
						</motion.div>
					</>
				)}
			</AnimatePresence>
		</div>
	);
}

export default function ContactsPage() {
	return (
		<Suspense fallback={<div className="p-8 text-center text-text-light">Loading contacts module...</div>}>
			<ContactsContent />
		</Suspense>
	);
}
